import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-[#f2f4f8]">
        {/* 앱 전체를 모바일 프레임(최대 430px) 기준으로 배치하고,
            오버레이/슬라이드 메뉴의 absolute 좌표 기준점이 되도록 relative를 부여합니다. */}
        <div className="relative mx-auto h-[100dvh] w-full max-w-[430px]">
          {children}
        </div>
      </body>
    </html>
  );
}
